name: iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          cache: true
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ios.app
          path: build/ios/iphoneos/Runner.app

  release:
    name: Release
    runs-on: macos-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: '.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}