name: Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: build/web/
